---
name: pipeline
on:
  push:
   branches: [ runner-test ]

jobs:
  GitHub-Actions-Self-Hosted-Runners:
    runs-on: mx-ts-vanilla-spa
    steps:
    - uses: actions/checkout@v3

    - uses: azure/setup-kubectl@v4
      id: install

    - run: |
        echo "ðŸŽ‰ This job uses runner scale set runners!"
        kubectl get pods -n github-runner-controller

    - run: kubectl apply -f $GITHUB_WORKSPACE/2048.yml -n default

# jobs:
#   deployment:
#     runs-on: 'ubuntu-latest'
#     steps:
#      - uses: actions/checkout@v3

#      - name: Deploy
#        uses: WyriHaximus/github-action-helm3@v3
#        with:
#           exec: helm repo add bitnami https://charts.bitnami.com/bitnami && helm repo update && helm install nginx bitnami/nginx 
#           kubeconfig: '${{ secrets.KUBECONFIG }}'
